version: '3.8'

services: 

    reverse_proxy:
      image: nginx
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./config/nginx:/etc/nginx
        - ./certs:/etc/ssl/private
      networks: 
        - backend

    leaderboardapi:
      build: .
      ports:
        - 8080:80
      networks: 
        - logging
        - backend

    mongo:
      image: mongo
      restart: always
      volumes:
        - ~/data:/data/db
      ports:
        - 27017:27017
      networks: 
        - backend

    mongo-express:
      image: mongo-express
      restart: always
      ports: 
        - 8081:8081
      networks: 
        - backend

    prometheus:
      image: prom/prometheus
      restart: always
      ports:
        - 9090:9090
      volumes:
        - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      networks: 
        - backend

    grafana:
      image: grafana/grafana
      restart: always
      environment:
        - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
        - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      ports:
        - 3000:3000
      volumes: 
        - ./grafana-storage:/var/lib/grafana
      networks: 
        - backend
networks: 
  logging:
    external: 
      name: logging
  backend: {}
