version: '3.8'

services: 
    leaderboardapi:
      build: .
      networks: 
        - backend

networks: 
  loadtest:
    external:
      name: loadtest
  backend:
    external: 
      name: backend
